/**
 * codegen.ts — generates Bun/Vitest test source from ResolvedEndpoint[].
 *
 * No template library. Uses native string concatenation + dedent helper.
 */

import { slugify } from "../utils/fmt.ts";
import type { GeneratedFile, ResolvedEndpoint, SwagenConfig } from "./types.ts";

export function generateTestFiles(
  endpoints: ResolvedEndpoint[],
  config: SwagenConfig,
  runner: "bun" | "vitest" = config.runner,
): GeneratedFile[] {
  const byTag = groupByTag(endpoints);
  const files: GeneratedFile[] = [];

  for (const [tag, tagEndpoints] of byTag) {
    files.push({
      relativePath: `${config.outDir}/${slugify(tag)}.test.ts`,
      content: renderTagFile(tag, tagEndpoints, config, runner),
      testCount: tagEndpoints.length,
    });
  }

  if (config.emitSetup) files.push(renderSetupFile(config));
  if (config.emitFixtures) files.push(renderFixturesFile(config));

  return files;
}

// ─── File renderers ───────────────────────────────────────────────────────────

function renderTagFile(
  tag: string,
  endpoints: ResolvedEndpoint[],
  config: SwagenConfig,
  runner: "bun" | "vitest",
): string {
  const importLine =
    runner === "vitest"
      ? `import { describe, it, expect, beforeAll, afterAll } from "vitest";`
      : `import { describe, it, expect, beforeAll, afterAll } from "bun:test";`;

  const setupImport = config.emitSetup ? `import { setup, teardown } from "./setup.js";` : "";
  const fixtureImport = config.emitFixtures ? `import { fixtures } from "./fixtures.js";` : "";

  const testBlocks = endpoints.map((ep) => renderTestCase(ep, config)).join("\n\n");

  return [
    `// Generated by swagen — do not edit manually`,
    `// Re-generate: swagen generate <spec> --runner ${runner}`,
    ``,
    importLine,
    setupImport,
    fixtureImport,
    ``,
    `const BASE_URL = ${config.baseUrl};`,
    ``,
    config.emitSetup
      ? [
          `beforeAll(async () => { await setup(); });`,
          `afterAll(async () => { await teardown(); });`,
          ``,
        ].join("\n")
      : "",
    `describe("${tag}", () => {`,
    indent(testBlocks, 2),
    `});`,
    ``,
  ]
    .filter(Boolean)
    .join("\n");
}

function renderTestCase(ep: ResolvedEndpoint, config: SwagenConfig): string {
  const testMod = ep.deprecated ? "it.skip" : "it";
  const title = `${ep.method.toUpperCase()} ${ep.path}`;

  const urlExpr = buildUrlExpr(ep, config);
  const fetchOpts = buildFetchOpts(ep, config);
  const asserts = buildAssertions(ep, config);

  return [
    `${testMod}("${title}", async () => {`,
    `  const url = ${urlExpr};`,
    `  const res = await fetch(url, ${fetchOpts});`,
    ...asserts.map((a) => `  ${a}`),
    `}, ${config.testTimeoutMs});`,
  ].join("\n");
}

function buildUrlExpr(ep: ResolvedEndpoint, _config: SwagenConfig): string {
  const pathParams = ep.params.filter((p) => p.in === "path");
  const queryParams = ep.params.filter((p) => p.in === "query");

  let pathExpr = "`${BASE_URL}" + ep.path + "`";
  for (const pp of pathParams) {
    pathExpr = pathExpr.replace(`{${pp.name}}`, `\${${sampleLiteral(pp)}}`);
  }

  if (queryParams.length === 0) return pathExpr;

  const qLines = queryParams.map(
    (p) => `    url.searchParams.set("${p.name}", String(${sampleLiteral(p)}));`,
  );
  return [
    "(() => {",
    `  const url = new URL(${pathExpr});`,
    ...qLines,
    "  return url.toString();",
    "})()",
  ].join("\n");
}

function buildFetchOpts(ep: ResolvedEndpoint, config: SwagenConfig): string {
  const headers = buildHeaders(ep, config);
  const parts = [`method: "${ep.method.toUpperCase()}"`, `headers: ${headers}`];

  if (ep.body?.contentType.includes("json")) {
    const sample = buildSampleBody(ep.body.schema);
    parts.push(`body: JSON.stringify(${JSON.stringify(sample, null, 2)})`);
  }

  return `{\n${parts.map((p) => "  " + p).join(",\n")}\n}`;
}

function buildHeaders(ep: ResolvedEndpoint, config: SwagenConfig): string {
  const h: Record<string, string> = {};

  switch (config.auth.type) {
    case "bearer":
      h["Authorization"] = `\`Bearer \${process.env.${config.auth.envVar ?? "API_TOKEN"}}\``;
      break;
    case "apiKey":
      if (config.auth.headerName) {
        h[config.auth.headerName] = `process.env.${config.auth.envVar ?? "API_KEY"} ?? ""`;
      }
      break;
    case "basic":
      h["Authorization"] = `\`Basic \${process.env.${config.auth.envVar ?? "API_CREDENTIALS"}}\``;
      break;
  }

  for (const p of ep.params.filter((prm) => prm.in === "header")) {
    h[p.name] = sampleLiteral(p);
  }

  if (ep.body?.contentType.includes("json")) h["Content-Type"] = '"application/json"';

  if (Object.keys(h).length === 0) return "{}";
  const lines = Object.entries(h).map(([k, v]) => `  "${k}": ${v}`);
  return `{\n${lines.join(",\n")}\n}`;
}

function buildAssertions(ep: ResolvedEndpoint, config: SwagenConfig): string[] {
  const primaryResp =
    ep.responses.find((r) => typeof r.statusCode === "number" && r.statusCode < 300) ??
    ep.responses[0];
  const expectedStatus = typeof primaryResp?.statusCode === "number" ? primaryResp.statusCode : 200;
  const a: string[] = [];

  if (config.assertStatusCodes) {
    a.push(`expect(res.status).toBe(${expectedStatus});`);
  } else {
    a.push(`expect(res.status).toBeGreaterThanOrEqual(200);`);
    a.push(`expect(res.status).toBeLessThan(500);`);
  }

  if (primaryResp?.contentType?.includes("json")) {
    a.push(`const body = await res.json();`);
    a.push(`expect(body).toBeDefined();`);
  }

  return a;
}

function buildSampleBody(schema: unknown): Record<string, unknown> {
  const s = schema as Record<string, unknown> | undefined;
  if (!s || s["type"] !== "object") return {};
  const props = s["properties"] as Record<string, Record<string, unknown>> | undefined;
  if (!props) return {};
  return Object.fromEntries(
    Object.entries(props).map(([k, v]) => [k, JSON.parse(sampleLiteral({ schema: v }))]),
  );
}

function sampleLiteral(param: { schema: unknown; example?: unknown }): string {
  if (param.example !== undefined) return JSON.stringify(param.example);
  const s = param.schema as Record<string, unknown> | undefined;
  switch (s?.["type"]) {
    case "integer":
    case "number":
      return "1";
    case "boolean":
      return "true";
    case "array":
      return "[]";
    case "object":
      return "{}";
    default:
      return '"TODO"';
  }
}

function renderSetupFile(config: SwagenConfig): GeneratedFile {
  return {
    relativePath: `${config.outDir}/setup.ts`,
    content: [
      `/** Shared setup — customize freely, won't be overwritten. */`,
      `export async function setup(): Promise<void> {}`,
      `export async function teardown(): Promise<void> {}`,
      ``,
    ].join("\n"),
    testCount: 0,
  };
}

function renderFixturesFile(config: SwagenConfig): GeneratedFile {
  return {
    relativePath: `${config.outDir}/fixtures.ts`,
    content: [
      `/** Shared fixtures — customize freely, won't be overwritten. */`,
      `export const fixtures = {`,
      `  // e.g. userId: "usr_test_123",`,
      `};`,
      ``,
    ].join("\n"),
    testCount: 0,
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function groupByTag(endpoints: ResolvedEndpoint[]): Map<string, ResolvedEndpoint[]> {
  const map = new Map<string, ResolvedEndpoint[]>();
  for (const ep of endpoints) {
    const tag = ep.tags[0] ?? "general";
    map.set(tag, [...(map.get(tag) ?? []), ep]);
  }
  return map;
}

function indent(s: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return s
    .split("\n")
    .map((l) => (l.trim() ? pad + l : l))
    .join("\n");
}
